### ISSUE TITLE
Litestack breaks rails database tasks in Rails ~> 7.2

### ISSUE THREAD

**Issue by alexspark** [oldmoe/litestack#128]
I've tested these set of commands on rails 7.2.1, 7.2.0, and 7.1.3.4 and it only works on 7.1.3.4

1. rails new litestack-app && cd litestack-app
2. bundle add litestack
3. bin/rails g litestack:install
4. bin/rails db:create

The error I get is on ~> 7.2 versions is as follows:

```
bin/rails aborted!
NoMethodError: undefined method `sqlite3_production_warning=' for class ActiveRecord::Base (NoMethodError)

Tasks: TOP => db:migrate => db:load_config
(See full trace by running task with --trace)
```

I tried to look at the rails 7.2 Changelogs but couldn't find any changes related to that configuration

**Comment by alexspark** [comment]
Rails 7.1.3.4 assigns `sqlite3_production_warning` to `true` [here](https://github.com/rails/rails/blob/v7.1.3.4/activerecord/lib/active_record/railtie.rb#L34), but 7.2 no longer assigns it in that same [section](https://github.com/rails/rails/blob/v7.2.0/activerecord/lib/active_record/railtie.rb#L34) of code.

but it's strange that litestack's railtie can even reach the assignment b/c of the `key?` guard [here](https://github.com/oldmoe/litestack/blob/83a1dc5f788bee673a696ca2d6df551a84799bb4/lib/litestack/railtie.rb#L6)

**Comment by adrienpoly** [comment]
This has been fix on main https://github.com/oldmoe/litestack/pull/106
The current solution is to get the gem from the main branch

**Comment by Schwad** [comment]
> This has been fix on main https://github.com/oldmoe/litestack/pull/106

Thanks for the tip!

**Comment by oldmoe** [comment]
I have been away from Litestack for the past few weeks (vacation + family),
will hopefully get around to releasing a new gem in the coming week or two

**Comment by bitshaker** [comment]
#

> I've tested these set of commands on rails 7.2.1, 7.2.0, and 7.1.3.4 and it only works on 7.1.3.4
> 
> 1. rails new litestack-app && cd litestack-app
> 2. bundle add litestack
> 3. bin/rails g litestack:install
> 4. bin/rails db:create
> 
> The error I get is on ~> 7.2 versions is as follows:
> 
> ```
> bin/rails aborted!
> NoMethodError: undefined method `sqlite3_production_warning=' for class ActiveRecord::Base (NoMethodError)
> 
> Tasks: TOP => db:create => db:load_config
> (See full trace by running task with --trace)
> ```
> 
> I tried to look at the rails 7.2 Changelogs but couldn't find any changes related to that configuration (EDIT: nvm found some changes. see comment below)

I get the same error when I do this on 8.0.0

I tried adding this to my Gemfile

`gem "litestack", github: "oldmoe/litestack", branch: "master"`

Running `bundle update`

I get

```bash
➜  litestack-app git:(main) ✗ bundle install
Fetching https://github.com/oldmoe/litestack.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions

Because every version of litestack depends on sqlite3 >= 1.6.0, < 2.0.0
  and Gemfile depends on sqlite3 >= 2.1,
  litestack cannot be used.
So, because Gemfile depends on litestack >= 0,
  version solving has failed.
```

**Comment by oldmoe** [comment]
I am  planning a new release soon, and I will remove the sqlite3 version
restriction in the process

**Comment by Gleaminggorillas** [comment]
@bitshaker thankyou!


>  I tried adding this to my Gemfile
>  ```
>  gem "litestack", github: "oldmoe/litestack", branch: "master"
>  ```
>  Running bundle update


this works for me using:
- ruby v3.4.1
- rack v3.1.8
- rails v8.0.1

EDIT:

also, added this into _config/environments/production.rb_: 
`config.active_record.sqlite3_production_warning`

**Comment by faqndo97** [comment]
Hi! I faced this problem yesterday and after some research I came across this issue. As mention by @bitshaker I solved the problem pointing to master on github, hopefully a new version will be created soon with this fix, but for now that's the fix.
